services:
  - type: web
    name: tienda-calzado
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      pip install gunicorn whitenoise Pillow
      python manage.py collectstatic --noinput
    startCommand: bash -lc "python manage.py migrate --noinput && python manage.py loaddata productos || true && gunicorn tienda.wsgi"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
